// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _00.Play.TicTacToe.Data._DbContext;

#nullable disable

namespace _00.Play.TicTacToe.Data.Migrations
{
    [DbContext(typeof(TicTacToeDbContext))]
    [Migration("20220427140623_db_init")]
    partial class db_init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Data.Infrastructure.Data._Entities.GameEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateTimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Difficulty")
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsComputer")
                        .HasColumnType("bit");

                    b.Property<string>("Player1_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Player2_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StartFirst")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("_GameId")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Game", (string)null);
                });

            modelBuilder.Entity("Data.Infrastructure.Data._Entities.MovesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateTimeMove")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("MoveFrom")
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("MoveNumber")
                        .HasColumnType("int");

                    b.Property<string>("MoveTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("_GameId")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Moves", (string)null);
                });

            modelBuilder.Entity("Data.Infrastructure.Data._Entities.ScoresTableEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerName");

                    b.ToTable("ScoresTable", (string)null);
                });

            modelBuilder.Entity("Data.Infrastructure.Data._Entities.TotalGamesEasyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<int>("StartFirst")
                        .HasColumnType("int");

                    b.Property<int>("StartSecond")
                        .HasColumnType("int");

                    b.Property<int>("Ties")
                        .HasColumnType("int");

                    b.Property<int>("TotalGames")
                        .HasColumnType("int");

                    b.Property<int>("TotalGamesVsComputerId")
                        .HasColumnType("int");

                    b.Property<int>("Victories")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TotalGamesVsComputerId")
                        .IsUnique();

                    b.ToTable("TotalGamesEasy", (string)null);
                });

            modelBuilder.Entity("Data.Infrastructure.Data._Entities.TotalGamesHardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<int>("StartFirst")
                        .HasColumnType("int");

                    b.Property<int>("StartSecond")
                        .HasColumnType("int");

                    b.Property<int>("Ties")
                        .HasColumnType("int");

                    b.Property<int>("TotalGames")
                        .HasColumnType("int");

                    b.Property<int>("TotalGamesVsComputerId")
                        .HasColumnType("int");

                    b.Property<int>("Victories")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TotalGamesVsComputerId")
                        .IsUnique();

                    b.ToTable("TotalGamesHard", (string)null);
                });

            modelBuilder.Entity("Data.Infrastructure.Data._Entities.TotalGamesIntermediateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<int>("StartFirst")
                        .HasColumnType("int");

                    b.Property<int>("StartSecond")
                        .HasColumnType("int");

                    b.Property<int>("Ties")
                        .HasColumnType("int");

                    b.Property<int>("TotalGames")
                        .HasColumnType("int");

                    b.Property<int>("TotalGamesVsComputerId")
                        .HasColumnType("int");

                    b.Property<int>("Victories")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TotalGamesVsComputerId")
                        .IsUnique();

                    b.ToTable("TotalGamesIntermediate", (string)null);
                });

            modelBuilder.Entity("Data.Infrastructure.Data._Entities.TotalGamesVsComputerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ScoreTableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScoreTableId")
                        .IsUnique();

                    b.ToTable("TotalGamesVsComputer", (string)null);
                });

            modelBuilder.Entity("Data.Infrastructure.Data._Entities.TotalGamesVsHumanEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<int>("ScoreTableId")
                        .HasColumnType("int");

                    b.Property<int>("StartFirst")
                        .HasColumnType("int");

                    b.Property<int>("StartSecond")
                        .HasColumnType("int");

                    b.Property<int>("Ties")
                        .HasColumnType("int");

                    b.Property<int>("TotalGames")
                        .HasColumnType("int");

                    b.Property<int>("Victories")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScoreTableId")
                        .IsUnique();

                    b.ToTable("TotalGamesVsHuman", (string)null);
                });

            modelBuilder.Entity("Data.Infrastructure.Data._Entities.MovesEntity", b =>
                {
                    b.HasOne("Data.Infrastructure.Data._Entities.GameEntity", "Game")
                        .WithMany("Moves")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Data.Infrastructure.Data._Entities.TotalGamesEasyEntity", b =>
                {
                    b.HasOne("Data.Infrastructure.Data._Entities.TotalGamesVsComputerEntity", "TotalGamesVsComputer")
                        .WithOne("TotalGamesEasy")
                        .HasForeignKey("Data.Infrastructure.Data._Entities.TotalGamesEasyEntity", "TotalGamesVsComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TotalGamesVsComputer");
                });

            modelBuilder.Entity("Data.Infrastructure.Data._Entities.TotalGamesHardEntity", b =>
                {
                    b.HasOne("Data.Infrastructure.Data._Entities.TotalGamesVsComputerEntity", "TotalGamesVsComputer")
                        .WithOne("TotalGamesHard")
                        .HasForeignKey("Data.Infrastructure.Data._Entities.TotalGamesHardEntity", "TotalGamesVsComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TotalGamesVsComputer");
                });

            modelBuilder.Entity("Data.Infrastructure.Data._Entities.TotalGamesIntermediateEntity", b =>
                {
                    b.HasOne("Data.Infrastructure.Data._Entities.TotalGamesVsComputerEntity", "TotalGamesVsComputer")
                        .WithOne("TotalGamesIntermediate")
                        .HasForeignKey("Data.Infrastructure.Data._Entities.TotalGamesIntermediateEntity", "TotalGamesVsComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TotalGamesVsComputer");
                });

            modelBuilder.Entity("Data.Infrastructure.Data._Entities.TotalGamesVsComputerEntity", b =>
                {
                    b.HasOne("Data.Infrastructure.Data._Entities.ScoresTableEntity", "ScoresTable")
                        .WithOne("TotalGamesVsComputer")
                        .HasForeignKey("Data.Infrastructure.Data._Entities.TotalGamesVsComputerEntity", "ScoreTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoresTable");
                });

            modelBuilder.Entity("Data.Infrastructure.Data._Entities.TotalGamesVsHumanEntity", b =>
                {
                    b.HasOne("Data.Infrastructure.Data._Entities.ScoresTableEntity", "ScoresTable")
                        .WithOne("TotalGamesVsHuman")
                        .HasForeignKey("Data.Infrastructure.Data._Entities.TotalGamesVsHumanEntity", "ScoreTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoresTable");
                });

            modelBuilder.Entity("Data.Infrastructure.Data._Entities.GameEntity", b =>
                {
                    b.Navigation("Moves");
                });

            modelBuilder.Entity("Data.Infrastructure.Data._Entities.ScoresTableEntity", b =>
                {
                    b.Navigation("TotalGamesVsComputer")
                        .IsRequired();

                    b.Navigation("TotalGamesVsHuman")
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Infrastructure.Data._Entities.TotalGamesVsComputerEntity", b =>
                {
                    b.Navigation("TotalGamesEasy");

                    b.Navigation("TotalGamesHard");

                    b.Navigation("TotalGamesIntermediate");
                });
#pragma warning restore 612, 618
        }
    }
}
